@startuml
读者"1"--"*"预订记录
读者--借书记录
图书管理员"1"--"*"借书记录 : 登记
预订记录"*"--"1"图书品种 : 被预定
借书记录"0..1"--"1"资源项
资源项"*"--*"1"图书品种
馆藏目录"1"--"1..*"图书品种
采购员"1"-"*"图书管理记录
图书管理员"1"--"*"图书管理记录 : 审核
购买图书--|>图书管理记录
淘汰图书--|>图书管理记录

class  馆藏目录{
}

class 资源项{
    馆藏流水号
    状态
}

class  读者{
    姓名
    身份证号
    借书卡号
    联系方式
    图书限额
    以借图书数
}
class  图书管理员{
    职工号
    姓名
    联系方式
}

class  采购员{
    职工号
    姓名
    联系方式
}

class 预订记录 {
    预定日期
    预订人
}

class 图书品种{
    作者
    出版社
    出版日期
    馆藏数量
    可借数量
}

class  借书记录{
    借书日期
    归还日期
}

class  图书管理记录{
    管理日期
    管理人员名字
    管理人员职工号
}

class 购买图书{
    购买日期
    图书数量
    图书品种
}

class 淘汰图书{
    淘汰日期
    图书数量
    图书品种
}

@enduml